CREATE TABLE IF NOT EXISTS config_opcoes_formulario (
  id SERIAL PRIMARY KEY,
  categoria text NOT NULL,
  nome text NOT NULL,
  valor text NOT NULL,
  is_ativo integer NOT NULL DEFAULT 1,
  created_at text DEFAULT CURRENT_TIMESTAMP,
  updated_at text DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (categoria, valor)
);

INSERT INTO config_opcoes_formulario (categoria, nome, valor)
VALUES
  ('evento_adverso', 'Hematoma pós-puncionismo', 'hematoma_pos_puncionismo'),
  ('evento_adverso', 'Pseudoaneurisma', 'pseudoaneurisma'),
  ('evento_adverso', 'Flebite', 'flebite'),
  ('evento_adverso', 'Hematoma retroperitonial', 'hematoma_retroperitonial'),
  ('evento_adverso', 'Falha envolvendo cateter venoso', 'falha_cateter_venoso'),
  ('evento_adverso', 'Reação transfusional', 'reacao_transfusional'),
  ('evento_adverso', 'Broncoaspiração', 'broncoaspiracao'),
  ('evento_adverso', 'Falha na identificação à beira leito', 'falha_identificacao_beira_leito'),
  ('evento_adverso', 'Falha no uso da pulseira de identificação', 'falha_pulseira_identificacao'),
  ('evento_adverso', 'Falha na comunicação', 'falha_comunicacao'),
  ('evento_adverso', 'Lesão por pressão', 'lesao_por_pressao'),
  ('evento_adverso', 'Queda', 'queda'),
  ('evento_adverso', 'Erro de medicação', 'erro_medicacao'),
  ('evento_adverso', 'Erro de dispensação', 'erro_dispensacao'),
  ('evento_adverso', 'Erro de prescrição', 'erro_prescricao'),
  ('evento_adverso', 'Tecnovigilância', 'tecnovigilancia'),
  ('evento_adverso', 'Equimose', 'equimose'),
  ('evento_adverso', 'Risco de infecção', 'risco_infeccao'),
  ('evento_adverso', 'Dermatite por fraldas', 'dermatite_fraldas'),
  ('evento_adverso', 'Reação alérgica', 'reacao_alergica'),
  ('evento_adverso', 'Lesão por dispositivo', 'lesao_dispositivo'),
  ('evento_adverso', 'Skin Tears', 'skin_tears'),
  ('evento_adverso', 'Outros', 'outros_evento_adverso'),
  ('nao_conformidade', 'Falha de processo', 'falha_processo'),
  ('nao_conformidade', 'Falha na comunicação', 'falha_comunicacao'),
  ('nao_conformidade', 'Falha na documentação', 'falha_documentacao'),
  ('nao_conformidade', 'Outros', 'outros_nao_conformidade'),
  ('local_acesso', 'Radial', 'radial'),
  ('local_acesso', 'Femoral', 'femoral'),
  ('local_acesso', 'Outros', 'outros'),
  ('local_lesao', 'Sacra', 'sacra'),
  ('local_lesao', 'Glúteo', 'gluteo'),
  ('local_lesao', 'Calcâneo', 'calcaneo'),
  ('local_lesao', 'Pavilhão auricular', 'pavilhao_auricular'),
  ('local_lesao', 'Trocânter', 'trocanter'),
  ('flebite_tipo', 'Química', 'quimica'),
  ('flebite_tipo', 'Mecânica', 'mecanica'),
  ('flebite_tipo', 'Infecciosa', 'infecciosa'),
  ('flebite_fator', 'Uso de amiodarona', 'amiodarona'),
  ('flebite_fator', 'Uso de antibióticos', 'antibioticos'),
  ('flebite_fator', 'Droga vasoativa', 'droga_vasoativa')
ON CONFLICT (categoria, valor) DO NOTHING;
